version: "3"
services:
  bot:
    build: .
    ports:
      - "9221:9221"
    container_name: skadi_hoshino
    restart: on-failure
    volumes:
      - .:/home/HoshinoBot/HoshinoBot
    networks:
      - hosbot_net
networks:
  hosbot_net:
    driver: bridge
