name: hoshino
channels:
- conda-forge
- anaconda
dependencies:
- python=3.10
- aiocache
- aiofiles
- aiohttp~=3.8.1
- anyio
- beautifulsoup4~=4.9.0
- distro
- emoji
- fontTools
- fuzzywuzzy
- GitPython
- httpx
- imageio
- Jinja2~=2.11.2
- loguru
- lxml>=4.9.1
- MarkupSafe~=1.0
- matplotlib
- numpy~=1.22.3
- pathos
- Pillow~=9.1.0
- prettytable
- psutil
- pycryptodome
- pydantic
- pygtrie~=2.3.3
- python-Levenshtein
- pytz>=2019.3
- Quart=0.14.1
- requests>=2.23.0
- tinydb~=4.1.1
- typing_extensions
- werkzeug~=1.0.1
- wsproto
- opencv
- msgpack-python
- httpx
- pypinyin
- pyyaml
- strenum
- urllib3~=1.26
- ujson
- pip:
  - aiocqhttp~=1.4.0
  - bbcode
  - cloudscraper~=1.2.60
  - nonebot[scheduler]==1.8.0
  - peony-twitter[all]~=2.1.2
  - sogou_tr_free~=0.0.8
  - zhconv~=1.4.1
  - meme_generator==0.1.13
  - arclet-alconna
  - opencc-python-reimplemented
